### ISSUE TITLE
Game of Code

### ISSUE THREAD

**Issue by petzlux** [to4dy/GameOfCode2016_DevNull_Team#2]
I hope you dont mind, but I have posted your contribution on our Open Data Portal as a reuse. Thanks for your participation!

https://data.public.lu/en/reuses/game-of-traffic/

**Comment by to4dy** [comment]
Hello,
Thank you, no problem.

**Comment by petzlux** [comment]
If you want, I can transfer ownership of the reuse to your account on the portal.

**Comment by to4dy** [comment]
This would be great, but if you prefer having all Game of Codes apps in on one account it's also okay.
